{% set version = '1.0-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-binhf
  version: {{ version|replace("-", "_") }}

source:
  fn: binhf_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/binhf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/binhf/binhf_{{ version }}.tar.gz
  sha256: be80a2f060e13e9aee33372f7c7971803169eb95840d8a9a7ae7b6f69116bced

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-ebayesthresh
    - r-adlift >=0.9.2
    - r-wavethresh
  run:
    - r-base
    - r-ebayesthresh
    - r-adlift >=0.9.2
    - r-wavethresh

test:
  commands:
    - $R -e "library('binhf')"           # [not win]
    - "\"%R%\" -e \"library('binhf')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=binhf
  license: GPL (>= 2)
  summary: Binomial Haar-Fisz transforms for Gaussianization as in Nunes and Nason (2009).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
