travis:
  secure:
    BINSTAR_TOKEN: AsaoPNWTsuEgb0A+CDDmiufofej8icX/HEBeOjK4eOSFnpSrLc4+dNlpIi9AlDSS4za1tG5e28NqFwVpy6Zirmmn+ockqYZGJnqjP3qyqx/plAfrv0rUa9zepfKQWQCbBJqjArZlLtD75QBVjfKZQ2/mC11l323WpALVLv0Ld8Zh7q/jH711xu4cYmLLtHzPh607x7/JU51GtdfGHNhNiftMgP0RXpaMEIWwa9Z5pEJqa6GY1r1nWVX9oLGz2QxrnL4Bpslmd4hOu+5SmhpqJPjFS1C1DTFZ6cMhzRzFKk/xjwahfp4IdZNdlC7nLgCpRbOXCB2Gq/qvZmWY5GBpa5FLMshRpQeYJqC0bpLoQcRvXgG9gLXFDplPCcCw0dDN8IwKh6rBkBwYgnyW3lCe4P8cFkxSBhOG+VX8fAXuaMlmMwTYwLQezmZhxaxMeHZEISdswGjeFFOjwL6o1ZKJcIJWEotewXpebUOIbmN1THaP9RAXSUQrIv6Bx3kyPxxW5LRdtCRIsFryJr+AUnmRjvtcKLnawemXM9bELqiYPAcU40Wkpu/1Y+Gh0VApb7jwHC4cTGMijKsltAC6JlnlGT8iBGnP8Cwx6NYq8WOu1aq3E1sWmPMaYZu7uiwn4zI1iIme9dq+1PM8ty09s8be4LCvHetoNEY/r5xoHldXA44=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
