travis:
  secure:
    BINSTAR_TOKEN: A/TFDkTfcPJZJEU8R8UJ9233iawz2oaa1JKjdPwawjBT4hyH2MZZdFR5D2XGG0mhjEglcTsX0cGxXiRYZLjECCg/wEQDY1RjNjthDeElvBf9r+3AaCxa9FSqFz5b4xpmjDr0k0BTDZM3LvuRwNawBB4recOLZN3jjH+2pRqWQ3/uL3RBUVTcWYzpoJbPusFkzrBUyYYWOyqI+wkzcFlhHy90GckQuwejnZI41VeGNVGHRMpJgvuWs79YhBeZ8Jb+eCDnqrAWDNmF+QppICiCd2sjq4Y6z1ei+kRAKNcWqoKilxJ4yqI96brI4BHx9cGHF2Xog6is7xcT5dHqYKTU6ix/UxQFj/UMLl89QssccCAFepvoW8LvTXXK2kOVmoyZ1R9wBNzBQSdJm7oyDa+v05JR3FzearJnVmd8rNW+b4WjoIJ2T890pna/nJ5qZXRVg+/lDQOX1StTsghCfQ/CiMyUOFP3G+46mlNsPARK/CviNmis3P0z/kVE9kUF5ZomB029vcU5WPPuEzwhICVs6idfqUUUgtW/R8dTn4mKk3Up/IyIv7WkX+wxIgAOiJNaRCs7cckhu9p4VkEH5GiFwdJK/zGeLIMdA6qJ+8K9gwwe21rNBj9qnUik9SS2EjpltLwrasSr37NkHNY0oMJWECiWygVbeSVfieiOLlwzhYs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
