travis:
  secure:
    BINSTAR_TOKEN: ja6Su3h48GN58c+jrz6Ky/fMONAxEDVacBAC29IfdMVXR6VX4txpmtEwkawX40yui+3spkugiBoAOfSABfmc/qsLHcH0GSrXn5Hq20rj7xj+sj0R7YAV+kp1G0KdPnF8sakGbsQ7OB3KvfM9J8+VDuNzOAHqQQ1Ma4BG9VP3ZzSd4tjZnhQX+mslEdz4Ea9kygUm4mG1id/ZkVmQYTtmp8p4eirn6ddXn9WJ3sjCBaLRzxZ3LpxEwISQEnoD5cGdDgd4o3Hlfer1/NZwwH+saxrtxI2NWmhm/MvvnIZYR0BQgBR/3ZMj7lTGiipqbJW45p7LCOfjl2HSNbjfyNsMlupsPd5cgfjeN5sf6+040H4pH4L4qTbBvq9CXRAnSz1Us7Ov1EOtr1GedfCVW8F6Ispl72kRW/xKH1B2kotu3C20YgzuIyOVpm57gd3NzaZs7kE8dbXSM7OYChpwVQ5d0zwdlakmINO5OUe5m0Zkx2ikmSLHiaWj2XNnbxhMp+w/12pzWcV0PgTeGMZvdZ4/LhknhJpA2tk6OzKKeXwXRtjcJX5dYRSaSH4LH4zukKwVkK2lGSGYbKMliwk+V8Qcu8krfx3Usr9Ugm+03CS+VwDVny4W8AfmAG4DhzT23UTy2In/nSZetcWt/PThAT7y/9Rv+uWw1BWfe99bwDtIwME=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
