appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QfceAaq2+HFOChCfo50XSGPqsJr3XJ9aJ5ZTlAfPHFWcWz3WQCueEdsCmresWglNzfmmHW9RdG4lRdvOW7niX2mItGjrbiIBBf3CvxYro3rUZsnBya8yHsO3FII5UhVWSzVX+ov86eoOQgPyVF7GHxWaIZeZNS989IvfgLZllVWTEtZAWw0GDMGby1DyfP2x7ODB772V/1caI8ybclSjmADLND3LKmj7oikQGGeA3AFB2gGswAgHgTjWjyXxo+z/akyAFFKkm7eYASRK7R5iWiEKT9iWs/cMnvySw3WTqXIk/sXhyfBAF6HO0C2bYnok65gy1TsOrvrtw2zjEJzWGDhHMaXjs6gxobJg4LmN1GSnQYFTjsvYqhMhPvojBQoCM7DKrfprgRSxJK4hgKYrSr2gstWzOZTzEUqbL/W0QywIgJx91/3wLD+FoL2IlLS3QvvaEEgPzz9/hlLy1RK3upItLveoJvV//HoiyumsInwJZuBhZIDZ4n+Y5X21mIlOKPooytgo2P1lT4/Zy43Ubdf9UQ2aXP7RBJnmSOdOPJ9saoZqiW2o3izF5VSXRBkhxYBcA/fizUyLmWUeOONEzTAnBKgdRjWraK7FlBgFpwYbWlc7Q1hfLBaE/1TAumWyVa58F3xGfAFTq1774UyumYrGYrHly2YpBGT9DVY9eiM=}
